export const CREATE_CHAMPION = "CREATE_CHAMPION";
export const RETRIEVE_CHAMPIONS = "RETRIEVE_CHAMPIONS";
export const UPDATE_CHAMPION = "UPDATE_CHAMPION";
export const DELETE_CHAMPION = "DELETE_CHAMPION";
export const DELETE_ALL_CHAMPIONS = "DELETE_ALL_CHAMPIONS";